#!/bin/bash
# OpenMES — Installer
# Generates .env with secure defaults and starts the stack.
# Run once on a fresh server: bash install.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✓ $*${NC}"; }
warn() { echo -e "${YELLOW}! $*${NC}"; }
err()  { echo -e "${RED}✗ $*${NC}"; exit 1; }
info() { echo -e "${CYAN}→ $*${NC}"; }

echo ""
echo "  ██████╗ ██████╗ ███████╗███╗   ██╗███╗   ███╗███████╗███████╗"
echo "  ██╔═══██╗██╔══██╗██╔════╝████╗  ██║████╗ ████║██╔════╝██╔════╝"
echo "  ██║   ██║██████╔╝█████╗  ██╔██╗ ██║██╔████╔██║█████╗  ███████╗"
echo "  ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║██║╚██╔╝██║██╔══╝  ╚════██║"
echo "  ╚██████╔╝██║     ███████╗██║ ╚████║██║ ╚═╝ ██║███████╗███████║"
echo "   ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝     ╚═╝╚══════╝╚══════╝"
echo ""
echo "  Manufacturing Execution System"
echo "  ──────────────────────────────────────────────────────────────"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
    err "Docker is not installed. See: https://docs.docker.com/get-docker/"
fi

if ! docker compose version &>/dev/null; then
    err "Docker Compose plugin not found. Install docker-compose-plugin."
fi

ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
ok "Docker Compose $(docker compose version --short)"
echo ""

# ── Existing installation check ───────────────────────────────────────────────

if [ -f ".env" ]; then
    warn ".env already exists — OpenMES may already be installed."
    read -rp "  Re-run setup? This will NOT delete existing data. (yes/no): " CONFIRM
    [ "$CONFIRM" = "yes" ] || { echo "Aborted."; exit 0; }
    echo ""
fi

# ── Helper: generate random password ─────────────────────────────────────────

gen_pass() {
    # 24 chars, alphanumeric + symbols safe for shell/env files
    tr -dc 'A-Za-z0-9@#%^&*_+=' </dev/urandom 2>/dev/null | head -c24 || \
    python3 -c "import secrets,string; print(secrets.token_urlsafe(18))"
}

# ── Collect configuration ─────────────────────────────────────────────────────

info "Configure your installation (press Enter to accept defaults):"
echo ""

read -rp "  Domain (e.g. demo.example.com) [localhost]: " DOMAIN
DOMAIN="${DOMAIN:-localhost}"

if [ "$DOMAIN" = "localhost" ]; then
    APP_URL="http://localhost"
else
    APP_URL="https://${DOMAIN}"
fi

read -rp "  Admin username [admin]: " ADMIN_USERNAME
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

read -rp "  Admin email [admin@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"

echo ""
info "Generating secure passwords..."

DB_PASSWORD="$(gen_pass)"
ADMIN_PASSWORD="$(gen_pass)"

echo ""
echo "  Generated credentials (save these now):"
echo "  ┌─────────────────────────────────────────┐"
echo "  │  Admin login:    ${ADMIN_USERNAME}"
echo "  │  Admin password: ${ADMIN_PASSWORD}"
echo "  │  DB password:    ${DB_PASSWORD}"
echo "  └─────────────────────────────────────────┘"
echo ""

read -rp "  Saved? Proceed with installation? (yes/no): " CONFIRM
[ "$CONFIRM" = "yes" ] || { echo "Aborted."; exit 0; }
echo ""

# ── Write .env ────────────────────────────────────────────────────────────────

cat > .env << EOF
# OpenMES — Docker Compose configuration
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── Domena i HTTPS ────────────────────────────────────────────────────────────
DOMAIN=${DOMAIN}
APP_URL=${APP_URL}

# ── Tryb pracy ────────────────────────────────────────────────────────────────
APP_ENV=production
APP_DEBUG=false

# ── Database ──────────────────────────────────────────────────────────────────
POSTGRES_DB=openmmes
POSTGRES_USER=openmmes_user
POSTGRES_PASSWORD=${DB_PASSWORD}

# ── Admin account (created automatically on first run) ────────────────────────
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

ok ".env created"

# ── Build and start ───────────────────────────────────────────────────────────

info "Building and starting containers (first build may take a few minutes)..."
echo ""

docker compose up -d --build

echo ""
ok "Containers started"
info "Waiting for application to be ready..."

ATTEMPTS=0
until curl -sf -o /dev/null "${APP_URL}" 2>/dev/null || curl -sf -o /dev/null "http://localhost" 2>/dev/null; do
    ATTEMPTS=$((ATTEMPTS + 1))
    [ $ATTEMPTS -gt 30 ] && { warn "App not responding after 60s — check: docker compose logs"; break; }
    sleep 2
done

echo ""
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║            OpenMES is ready!                             ║"
echo "  ║                                                          ║"
printf  "  ║  URL:      %-46s║\n" "${APP_URL}"
printf  "  ║  Login:    %-46s║\n" "${ADMIN_USERNAME}"
printf  "  ║  Password: %-46s║\n" "${ADMIN_PASSWORD}"
echo "  ║                                                          ║"
echo "  ║  Credentials are saved in .env (do not share this file) ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f backend       # Live logs"
echo "    docker compose down                  # Stop"
echo "    docker compose up -d                 # Start"
echo ""
